### ISSUE TITLE
Update conference planning with the talk descriptions

### ISSUE THREAD

**Issue by samvloeberghs** [ng-be/2016-www-ng-be-org#76]
The website should be updated with the current conference planning: 
- [ ] update planning
- [ ] link planning to speakers 
- [ ] todd's talk description
- [ ] ...

**Comment by SamVerschueren** [comment]
Will do it. I hope I can squeeze it in somewhere ASAP, otherwise it has to wait until after JS-BE :p.

**Comment by SamVerschueren** [comment]
@samvloeberghs Do you want something like this?

<img width="739" alt="screen shot 2016-11-23 at 22 01 34" src="https://cloud.githubusercontent.com/assets/1913805/20578756/3a90f928-b1c9-11e6-972a-50ec5a6436bb.png">

Or do you want the title of the talk instead of the full description? If so, where do we put the description of the talk? Or do you want a collapsable description?

Note: Links still have to be styled.

**Comment by samvloeberghs** [comment]
@SamVerschueren I think this is quite ok.. I would not go to far in it.
What I would suggest tough, is that you put the title of the talk first, than the link to the person doing it, and than the short description of the talk:

so
title
speaker
description

**Comment by SamVerschueren** [comment]
Good idea! Was also wondering if we should give the non-talks a slightly different color. But that might be too far.

**Comment by samvloeberghs** [comment]
@SamVerschueren could we lighten them up very subtle? ( sponsored talks, breaks, lunch, .. )

**Comment by samvloeberghs** [comment]
Todd motto's description:
In this talk we’ll take a deeper dive into Angular 2 Reactive forms and utilise the powerful APIs Angular 2 offers for complex forms, validation and much more.

**Comment by SamVerschueren** [comment]
<img width="747" alt="screen shot 2016-11-28 at 20 28 30" src="https://cloud.githubusercontent.com/assets/1913805/20682698/41de368a-b5a9-11e6-88d9-fb87090a2cbc.png">

Like this, or the other way around? Maybe too light?

**Comment by samvloeberghs** [comment]
Looks good to me!
